# Generated by Django 4.2.26 on 2025-11-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteshrinker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
