# Generated by Django 5.2.8 on 2025-11-13 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteshrinker", "0002_alter_picture_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_pdf",
                    models.FileField(
                        help_text="Main book PDF", upload_to="books/main/"
                    ),
                ),
                (
                    "cover_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Optional cover PDF",
                        null=True,
                        upload_to="books/covers/",
                    ),
                ),
                (
                    "optimized_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="books/optimized/"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("preview", "Preview Ready"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("original_size_mb", models.FloatField(blank=True, null=True)),
                ("optimized_size_mb", models.FloatField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("cover_page_count", models.IntegerField(blank=True, null=True)),
                ("processing_settings", models.JSONField(blank=True, default=dict)),
                ("session_key", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
    ]
